{% set name = "curl-cffi" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 62ecd90a382bd5023750e3606e0aa7cb1a3a8ba41c14270b8e5e149ebf72c5ca
  patches:
    - patches/0001-unvendor-curl-impersonate.patch

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - LIBDIR_PATH=$PREFIX/lib/ # [unix]
    - LIBDIR_PATH=%PREFIX%\\Library  # [win]
  ignore_run_exports:
    - zlib  # [win]
  missing_dso_whitelist:
    - $RPATH/api-ms-win-core-winrt-error-l1-1-0.dll   # [win]
    - $RPATH/api-ms-win-core-winrt-l1-1-0.dll         # [win]
    - $RPATH/api-ms-win-core-winrt-string-l1-1-0.dll  # [win]
    - $RPATH/libcrypto-3-x64.dll  # [win]
    - $RPATH/zstd.dll  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cffi 1.17.1  # oldest py313
    - curl-impersonate 1.2.0
  run:
    - python
    - cffi >=1.12.0
    - certifi >=2024.2.2
    - curl-impersonate # pinned by run_exports
  run_constrained:
    - markdownify >=1.1.0
    - readability-lxml >=0.8.1

test:
  imports:
    - curl_cffi
    - curl_cffi.const
    - curl_cffi.requests
    - curl_cffi.requests.cookies
    - curl_cffi.requests.errors
    - curl_cffi.requests.exceptions
    - curl_cffi.requests.models
    - curl_cffi.requests.utils
    - curl_cffi.utils
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Cannot run upstream tests. tests/unittest cannot be invoked due to lack of 'proxy' dependencies
    # tests/threads -> RuntimeError: cannot release un-acquired lock
    # tests/integration failing due to failing hash assertion and requests to https://httpbin.org/
    - test -f $SP_DIR/curl_cffi/_wrapper.abi3.so  # [unix]
    - if not exist %SP_DIR%\\curl_cffi\\_wrapper.pyd exit 1  # [win]
    
about:
  home: https://github.com/lexiforest/curl_cffi
  summary: libcurl ffi bindings for Python, with impersonation support.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Unlike other pure Python http clients like httpx or requests,
    curl_cffi can impersonate browsers’ TLS signatures or JA3
    fingerprints. If you are blocked by some website for no obvious
    reason, you can give this package a try.
  doc_url: https://curl-cffi.readthedocs.io
  dev_url: https://github.com/lexiforest/curl_cffi

extra:
  recipe-maintainers:
    - jan-janssen